openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /usernotes:
    get:
      tags:
      - usernote-controller
      operationId: getAllUsernotes
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - usernote-controller
      operationId: createPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usernote"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /auth/register:
    post:
      tags:
      - user-controller
      summary: 회원 가입 API
      description: 회원 가입에 성공하면 이메일 인증(2fa)을 거칩니다.
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: 2fa로 넘어갑니다. 추후 201 코드로 바뀔듯요
          content:
            '*/*':
              schema:
                type: object
  /auth/logout:
    post:
      tags:
      - user-controller
      summary: 로그아웃 API
      description: 이미 로그아웃되었으므로 아무것도 반환하지 않습니다.
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogoutRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /auth/login:
    post:
      tags:
      - user-controller
      summary: 로그인 API
      description: 2차인증이 필요하다면 2차인증 수속을 다시 밟고 이미 되었다면 JWT 토큰을 반환합니다.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /auth/check-email:
    post:
      tags:
      - user-controller
      summary: 우선 이메일 확인 API
      description: 이메일이 User DB에 있는지 확인합니다.
      operationId: checkEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmailCheckRequest"
        required: true
      responses:
        "200":
          description: 이메일이 존재
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmailCheckResponse"
        "404":
          description: 이메일 없음 ㅠㅠ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmailCheckResponse"
  /usernote/{id}:
    get:
      tags:
      - usernote-controller
      operationId: getUsernoteById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - usernote-controller
      operationId: deleteUsernote
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - usernote-controller
      operationId: updateUsernote
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usernote"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /auth/2fa:
    get:
      tags:
      - user-controller
      summary: 이메일 인증 API
      description: 해당되는 이메일로 링크가 전달됩니다.
      operationId: confirmEmail
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Usernote:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        likes:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        is2fa:
          type: boolean
        nickname:
          type: string
        password:
          type: string
        roles:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
            - USER
            - ADMIN
    LogoutRequestDto:
      required:
      - email
      type: object
      properties:
        email:
          type: string
    EmailCheckRequest:
      type: object
      properties:
        email:
          type: string
          description: 확인할 이메일 주소
          example: user@sookmyung.com
      description: 이메일 확인 여요청
    EmailCheckResponse:
      type: object
      properties:
        exists:
          type: boolean
          description: 이메일 존재 여부
          example: true
        message:
          type: string
          description: 응답 메시지
          example: 이메일이 확인되었습니다. 비밀번호를 입력해주세요.
      description: 이메일 확인 응답
